name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build
        run: |
          cd Team39/Code39
          mkdir build
          cd build
          cmake -A Win32 .. &&
          cmake --build . --target unit_testing --config Release &&
          cmake --build . --target integration_testing --config Release &&
          cmake --build . --target autotester --config Release
          if ($lastexitcode -ne 0) { throw "build failed" }
      - name: unit tests
        run: |
          cd Team39/Code39
          ./build/src/unit_testing/Release/unit_testing.exe
          if ($lastexitcode -ne 0) { throw "unit tests failed" }
      - name: integration tests
        run: |
          cd Team39/Code39
          ./build/src/integration_testing/Release/integration_testing.exe
          if ($lastexitcode -ne 0) { throw "integration tests failed" }
#       - name: run autotester
#         run: |
#           cd Team39/Code39
#           ..\Code34\build\src\autotester\Release\autotester.exe
#           if ($lastexitcode -ne 0) { throw "autotester failed" }
  
